site_name: R

theme:
  name: material

  features:
    - search.share
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  
  logo: assets/logo.svg
  
  favicon: assets/logo.svg
  
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: true


extra_css:
  - stylesheets/extra.css
